"""Domain Pydantic schemas that flow through Redis Streams.

These are higher-level objects (FeatureSnapshot, Decision, JournalEntry)
distinct from the connector-layer wire types in
:mod:`xauusd_bot.connectors.schemas`. The decision engine emits
:class:`Decision`; the feature engine emits :class:`FeatureSnapshot`;
the journal persists :class:`JournalEntry`. Each carries a stable
``schema_version`` so consumers can reject incompatible payloads.
"""

from xauusd_bot.common.schemas.events import (
    SCHEMA_VERSION,
    BarEvent,
    Decision,
    DecisionAction,
    FeatureSnapshot,
    JournalEntry,
    MarketData,
    OrderEvent,
    Side,
)
from xauusd_bot.common.schemas.ai_decision import (
    EntryZone,
    LLMDecision,
    ManagementBlock,
    REASON_HARD_RULE_VIOLATION,
    REASON_LLM_DISABLED,
    REASON_NEWS_BLACKOUT,
    REASON_NO_API_KEY,
    REASON_SCORE_BELOW_THRESHOLD,
    REASON_TIMEOUT,
    REASON_VALIDATION_ERROR,
    REASON_ZONE_VIOLATION,
)
from xauusd_bot.common.schemas.features import (
    CandleMomentumOutput,
    CandleMomentumPerBar,
    FeatureSnapshotBundle,
    FVGOutput,
    FVGStatus,
    FVGType,
    FVGZone,
    LiquidityEngineOutput,
    LiquidityPool,
    LiquidityZone,
    MarketStructureOutput,
    NewsContextOutput,
    NewsEvent,
    NewsImpact,
    SessionEngineOutput,
    SessionName,
    StructureEvent,
    StructureEventType,
    SwingPoint,
    TripleVWAPOutput,
    ValueAreaStatus,
    VolumeProfileName,
    VolumeProfileOutput,
    VolumeProfileState,
    VolumeRangeOutput,
    VWAPLevel,
    VWAPLevelOutput,
)
from xauusd_bot.common.schemas.journal import (
    LLMFallbackDiscrepancy,
    LLMFallbackDiscrepancyV2,
)
from xauusd_bot.common.schemas.review import (
    DataSufficiency,
    FeatureSnapshotLite,
    FittingProposal,
    FittingProposalFilter,
    FittingProposalStatus,
    KPISummary,
    LLMFallbackDiscrepancyLite,
    OverfittingRisk,
    ReviewCategory,
    ReviewOutput,
    ReviewProposal,
    ReviewRequest,
    ReviewRun,
    TradeSummary,
)

__all__ = [
    "BarEvent",
    "CandleMomentumOutput",
    "CandleMomentumPerBar",
    "Decision",
"DecisionAction",
    "EntryType",
    "FVGOutput",
    "FVGStatus",
    "FVGType",
    "FVGZone",
    "FeatureSnapshot",
    "FeatureSnapshotBundle",
    "FeatureSnapshotLite",
    "FittingProposal",
    "FittingProposalFilter",
    "FittingProposalStatus",
    "JournalEntry",
    "KPISummary",
    "LLMDecision",
    "LLMFallbackDiscrepancy",
    "LLMFallbackDiscrepancyLite",
    "LLMFallbackDiscrepancyV2",
    "LiquidityEngineOutput",
    "LiquidityPool",
    "LiquidityZone",
    "ManagementBlock",
    "MarketData",
    "MarketStructureOutput",
    "NewsContextOutput",
    "NewsEvent",
    "NewsImpact",
    "OrderEvent",
    "OverfittingRisk",
    "REASON_HARD_RULE_VIOLATION",
    "REASON_LLM_DISABLED",
    "REASON_NEWS_BLACKOUT",
    "REASON_NO_API_KEY",
    "REASON_SCORE_BELOW_THRESHOLD",
    "REASON_TIMEOUT",
    "REASON_VALIDATION_ERROR",
    "REASON_ZONE_VIOLATION",
    "ReviewCategory",
    "DataSufficiency",
    "ReviewOutput",
    "ReviewProposal",
    "ReviewRequest",
    "ReviewRun",
    "SCHEMA_VERSION",
    "SessionEngineOutput",
    "SessionName",
    "Side",
    "StructureEvent",
    "StructureEventType",
    "SwingPoint",
    "TradeSummary",
    "TripleVWAPOutput",
    "ValueAreaStatus",
    "VolumeProfileName",
    "VolumeProfileOutput",
    "VolumeProfileState",
    "VolumeRangeOutput",
    "VWAPLevel",
    "VWAPLevelOutput",
]
